version: '2'
services:
  bitwarden_dropbox_backup:
    image: nikolainvernizzi/bitwarden_rs_dropbox_backup:0.3
    restart: always
    volumes:
      - /bitwarden:/data 
      - /bitwarden-dropbox-backup/logs:/logs
      - /bitwarden-dropbox-backup/config:/config
      - /bitwarden-dropbox-backup/backups:/backups
    environment:
      - BACKUP_PREFIX=BitwardenBackup
      - BACKUP_ENCRYPTION_KEY=XXXX
      - DELETE_AFTER=10
      - KEEP_LOCAL_BACKUPS=1
      - CRON_EXPRESSION=0 1 * * *
