version: '3.2'
services:
  bitwarden_dropbox_backup:
    image: nikolainvernizzi/bitwarden_rs_dropbox_backup:latest
    restart: always
    volumes:
      - /home/user/bitwarden:/data 
      - /home/user/bitwarden-dropbox-backup/config:/config
      - /home/user/bitwarden-dropbox-backup/backups:/backups
    environment:
      - BACKUP_PREFIX=xxx
      - BACKUP_ENCRYPTION_KEY=xxx
      - DELETE_AFTER=10
      - MINIMUM_BACKUPS=10
